<?php if ($this->pageCount): ?>
    <ul class="pagination pagination-sm">
        <!-- Pevious page link-->
        <?php if (isset($this->previous)): ?>
            <li class="page-item"><a class="page-link" href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>"><<<</a></li>
        <?php else: ?>
            <li class="page-item disabled"><a class="page-link" href="#" onclick="return false;"><<</a></li>
        <?php endif; ?>

        <!--Numbered page link-->
        <?php   foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li><a class="page-link" href="<?= $this->url($this->route); ?>?page=<?= $page; ?>"><?= $page; ?></a></li>
            <?php else: ?>
            <li class="page-item active"><a class="page-link" class="page-link" href="#"><?= $page; ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
        <!--Next page link-->
        <?php if(isset($this->next)): ?>
            <li class="page-item">
                <a class="page-link" href="<?= $this->url($this->route); ?>?page=<?= $this->next; ?>">>>></a>
            </li>
        <?php else: ?>
            <li class="page-item disabled"><a class="page-link" href="#" onclick="return false;">>></a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>
